// examples/languages/vue/src/App.vue
<script setup lang="ts">
import CodatConnections from './components/CodatConnections.vue'
import { ref } from 'vue'
import type { DisconnectCallbackArgs, ReconnectCallbackArgs, ErrorCallbackArgs } from 'https://connections-sdk.codat.io'

const accessToken = ref('')
const modalOpen = ref(false)

const handleCloseModal = () => {
  modalOpen.value = false
}

const handleOnDisconnect = (connection: DisconnectCallbackArgs) => {
  alert(`On disconnect callback - ${connection.connectionId}`)
}

const handleOnReconnect = (connection: ReconnectCallbackArgs) => {
  alert(`On disconnect callback - ${connection.connectionId}`)
}

const handleOnClose = () => {
  handleCloseModal()
}

const handleOnError = (error: ErrorCallbackArgs) => {
  alert(`On error callback -${error.message}`)
  handleCloseModal()
}
</script>

<template>
  <main class="main">
    <header>
      <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
      <h1 class="title">
        <a target="_blank" rel="noreferrer" href="https://github.com/codatio/sdk-link-types/tree/main/examples/vue/README.md">
          Connections SDK x Vue
        </a>
      </h1>
    </header>
    <div class="content">
      <p>An example of embedding Connections SDK within a brand new create-vue project</p>
      <ol>
        <li>
          <a
            href="https://github.com/codatio/sdk-link-types/tree/main#set-cors-domains"
            target="_blank"
            rel="noreferrer"
          >
            Set CORS domains
          </a>
        </li>
        <li>
          <a href="https://github.com/codatio/sdk-link-types/tree/main#generate-access-token" target="_blank" rel="noreferrer">
            Generate an access token
          </a>
        </li>
        <li>Paste the access token below</li>
      </ol>
      <div class="inputWrapper">
        <textarea v-model="accessToken" placeholder="Provide a valid JWT"></textarea>
        <button @click="modalOpen = !modalOpen">
          {{ modalOpen ? 'Exit' : 'Start managing connections' }}
        </button>
      </div>

    </div>
    <div v-if="modalOpen" class="modalWrapper">
      <CodatConnections :access-token="accessToken" :on-disconnect="handleOnDisconnect" :on-close="handleOnClose"
        :on-reconnect="handleOnReconnect" :on-error="handleOnError" />
    </div>
  </main>
</template>

<style scoped>
.main {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 6rem;
  gap: 1rem;
  min-height: 100vh;
  box-sizing: border-box;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
}

.modalWrapper {
  align-items: center;
  box-sizing: border-box;
  display: flex;
  justify-content: center;
  position: fixed;
  inset: 0;
  z-index: 2;
}

.inputWrapper {
  display: flex;
  gap: .5rem
}
</style>

// examples/languages/svelte/src/App.svelte
<script lang="ts">
  import welcome from "./assets/svelte-welcome.webp";
  import Header from "./lib/Header.svelte";
  import welcome_fallback from "./assets/svelte-welcome.png";
  import "./styles.css";
  import CodatConnections from "./lib/CodatConnections.svelte";
  import type {
    DisconnectCallbackArgs,
    ReconnectCallbackArgs,
    ErrorCallbackArgs,
  } from "https://connections-sdk.codat.io";

  let modalOpen = false;
  let accessToken = "";

  const onDisconnect = (connection: DisconnectCallbackArgs) =>
    alert(`On disconnect callback - ${connection.connectionId}`);
  const onReconnect = (connection: ReconnectCallbackArgs) =>
    alert(`On reconnect callback - ${connection.connectionId}`);
  const onClose = () => (modalOpen = false);
  const onError = (error: ErrorCallbackArgs) =>
    alert(`On error callback - ${error.message}`);
</script>

<div class="app">
  <Header />
  <main>
    <span class="welcome">
      <picture>
        <source srcset={welcome} type="image/webp" />
        <img src={welcome_fallback} alt="Welcome" />
      </picture>
    </span>
    <h1>
      <a
        target="_blank"
        rel="noreferrer"
        href="https://github.com/codatio/sdk-link-types/blob/main/examples/svelte/README.md"
      >
        Connections SDK x Svelte
      </a>
    </h1>
    <p>An example of embedding Connections SDK within a Svelte App</p>
    <div>
      <ol>
        <li>
          <a
            href="https://github.com/codatio/sdk-link-types/tree/main#set-cors-domains"
            target="_blank"
            rel="noreferrer"
          >
            Set CORS domains
          </a>
        </li>
        <li>
          <a
            href="https://github.com/codatio/sdk-link-types/tree/main#generate-access-token"
            target="_blank"
            rel="noreferrer"
          >
            Generate an access token
          </a>
        </li>
        <li>Paste the access token below</li>
      </ol>
      <div class="input-wrapper">
        <textarea bind:value={accessToken} placeholder="Provide a valid JWT"
        ></textarea>
        <button
          on:click={() => {
            modalOpen = true;
          }}>Start managing connections</button
        >
      </div>
    </div>
    {#if modalOpen}
      <div class="modal-wrapper">
        <CodatConnections
          {accessToken}
          {onDisconnect}
          {onReconnect}
          {onClose}
          {onError}
        />
      </div>
    {/if}
  </main>
</div>

<style>
  .app {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
  }

  h1 {
    margin: 0;
  }

  main {
    flex: 0.6;
    display: flex;
    flex-direction: column;
    justify-content: start;
    align-items: center;
  }

  .welcome {
    display: block;
    position: relative;
    width: 100%;
    max-width: 1200px;
    margin-top: 20px;
    padding: 0 0 min(200px, calc(100% * 495 / 2048)) 0;
  }

  .welcome img {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    display: block;
  }
  .modal-wrapper {
    align-items: center;
    box-sizing: border-box;
    display: flex;
    justify-content: center;
    position: fixed;
    inset: 0;
  }
</style>
